[package]
name = "ironfish_rust"
version = "0.1.0"
authors = ["Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
edition = "2018"
license = "MPL-2.0"

[lib]
name = "ironfish_rust"
path = "src/lib.rs"


[dependencies]
zcash_primitives = {git = "https://github.com/iron-fish/librustzcash.git"}
zcash_proofs = {git = "https://github.com/iron-fish/librustzcash.git"}
bellman = {git = "https://github.com/iron-fish/librustzcash.git", version = "0.6", default-features = false, features = ["groth16"]}
pairing = { git = "https://github.com/iron-fish/librustzcash.git", version = "0.16", features = ["expose-arith"]}
ff = { git = "https://github.com/iron-fish/librustzcash.git",  version = "0.6"}
byteorder = "1.3.1"
lazy_static = "1.4.0"
# in favor of rust-crypto as this one is wasm friendly
rust-crypto-wasm="0.3.1"
rand = {version = "0.7", features = ["wasm-bindgen"]}
shrinkwraprs = "0.2.1"
tiny-bip39 = "0.8.0"
blake2b_simd = "0.5"
blake2s_simd = "0.5"
