
# cargo-vet audits file

[[audits.arrayvec]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.7.2 -> 0.7.4"

[[audits.bellman]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.13.1 -> 0.13.1@git:1cc52ca33e6db14233f1cbc0c9c5b7c822b229ec"
notes = "Fork of the official bellperson owned by Iron Fish"

[[audits.bellperson]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.24.1 -> 0.24.1@git:37b9976bcd96986cbdc71ae09fc455015e3dfac0"
notes = "Fork of the official bellperson owned by Iron Fish"

[[audits.crypto_box]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "0.9.1"

[[audits.equihash]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.2.0 -> 0.2.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official equihash owned by Iron Fish"

[[audits.f4jumble]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official f4jumble owned by Iron Fish"

[[audits.frost-core]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.h2]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.3.26"

[[audits.hashbrown]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.14.0 -> 0.14.3"

[[audits.hermit-abi]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.2.6 -> 0.3.3"

[[audits.indexmap]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "1.9.3 -> 2.2.6"

[[audits.jubjub]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.9.0 -> 0.9.0@git:6fac532975e23acd3fa670bc0383d027f09403e5"
importable = false
notes = "Fork of the official jubjub owned by Iron Fish"

[[audits.mio]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.8.8 -> 0.8.11"

[[audits.openssl]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.10.59 -> 0.10.64"

[[audits.openssl-sys]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.9.95 -> 0.9.102"

[[audits.reddsa]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.5.1 -> 0.5.1@git:311baf8865f6e21527d1f20750d8f2cf5c9e531a"
importable = false
notes = "Unreleased changes required by ironfish-frost to support multisig wallets"

[[audits.siphasher]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.zcash_address]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_address owned by Iron Fish"

[[audits.zcash_encoding]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_encoding owned by Iron Fish"

[[audits.zcash_note_encryption]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_note_encryption owned by Iron Fish"

[[audits.zcash_primitives]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.7.0 -> 0.7.0@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_primitives owned by Iron Fish"

[[audits.zcash_proofs]]
who = "Andrea <andrea@iflabs.network>"
criteria = "safe-to-deploy"
delta = "0.7.1 -> 0.7.1@git:d551820030cb596eafe82226667f32b47164f91b"
notes = "Fork of the official zcash_proofs owned by Iron Fish"
