name: Deploy Node Image to Github
on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Login to Github Registry
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_USER} --password-stdin ghcr.io
        env:
          GITHUB_USER: ${{ secrets.BREW_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}

      - name: Build Node Image
        run: ./ironfish-cli/scripts/build-docker.sh

      - name: Deploy Node Image to Github
        run: ./ironfish-cli/scripts/deploy-docker.sh
        env:
          REGISTRY_URL: ghcr.io/iron-fish
          PACKAGE_NAME: ironfish
