name: Deploy Brew Tap Release
on:
  workflow_dispatch:
    inputs:
      refToBuild:
        type: string

jobs:
  Deploy:
    name: Deploy
    runs-on: macos-13

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: nodejs

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build Ironfish CLI
        run: ./ironfish-cli/scripts/build.sh

      - name: Deploy Ironfish CLI Brew to R2
        run: ./ironfish-cli/scripts/deploy-brew.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          BREW_GITHUB_USERNAME: ${{ secrets.BREW_GITHUB_USERNAME }}
          BREW_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
          AWS_DEFAULT_REGION: auto
