name: Deploy HTTP API
on:
  push:
    branches:
      - beta
  paths:
    - 'ironfish-http-api-v2/**'

jobs:
  deploy:
    name: Staging API Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HEROKU_SSH_PRIVATE_KEY }}
      - name: Update known hosts
        run: ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
      - name: SSH Git with Heroku
        run: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
      - name: Add Heroku remote
        run: git remote add heroku $HEROKU_REMOTE
        env:
          HEROKU_REMOTE: ${{ secrets.HEROKU_REMOTE }}
      - name: Push to Heroku
        run: git push heroku -f `git subtree split --prefix ironfish-http-api-v2 HEAD`:master
