on:
  push:
    branches:
      - master
      - staging
    paths:
      - "ironfish-rust/**"
      - "ironfish-rust-nodejs/**"
      - "ironfish-zkp/**"
      - "ironfish-setup/**"
      - "rust-toolchain"
      - ".github/workflows/rust*"
      - ".cargo/**"
      - "Cargo*"

name: Cache Rust build

jobs:
  build-rust-cache:
    name: Build and cache rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: nodejs

      - name: Build NAPI bindings for the cache
        run: |
          cargo build --release
